# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path

base = Path(r"C:\Users\15978\Desktop\XMclaw")

block_cipher = None

a = Analysis(
    [str(base / "xmclaw" / "desktop" / "app.py")],
    pathex=[str(base)],
    binaries=[],
    datas=[
        (str(base / "web"), "web"),
        (str(base / "agents"), "agents"),
        (str(base / "daemon" / "config.json"), "daemon"),
        (str(base / "python"), "python"),
    ],
    hiddenimports=[
        "xmclaw.daemon.server",
        "xmclaw.daemon.config",
        "xmclaw.daemon.lifecycle",
        "xmclaw.daemon.static",
        "xmclaw.core.agent_loop",
        "xmclaw.core.orchestrator",
        "xmclaw.core.prompt_builder",
        "xmclaw.core.cost_tracker",
        "xmclaw.llm.router",
        "xmclaw.llm.openai_client",
        "xmclaw.llm.anthropic_client",
        "xmclaw.llm.streaming",
        "xmclaw.tools.registry",
        "xmclaw.tools.file_read",
        "xmclaw.tools.file_write",
        "xmclaw.tools.file_edit",
        "xmclaw.tools.bash",
        "xmclaw.tools.web_search",
        "xmclaw.tools.browser",
        "xmclaw.tools.todo",
        "xmclaw.tools.memory_search",
        "xmclaw.memory.manager",
        "xmclaw.memory.sqlite_store",
        "xmclaw.memory.session_manager",
        "xmclaw.evolution.engine",
        "xmclaw.evolution.scheduler",
        "xmclaw.evolution.vfm",
        "xmclaw.evolution.gene_forge",
        "xmclaw.evolution.skill_forge",
        "xmclaw.evolution.validator",
        "xmclaw.skills.manager",
        "xmclaw.genes.manager",
        "xmclaw.genes.base",
        "xmclaw.desktop.main_window",
        "xmclaw.desktop.ws_client",
        "xmclaw.cli.main",
        "xmclaw.cli.client",
        "xmclaw.cli.rich_ui",
        "xmclaw.utils.log",
        "xmclaw.utils.paths",
        "xmclaw.utils.security",
        "PySide6",
        "PySide6.QtCore",
        "PySide6.QtGui",
        "PySide6.QtWidgets",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="XMclaw",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
